name: Test
on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.21.x', '1.20.x', '1.19.x' ]
    name: Go ${{ matrix.go }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - name: Unit tests
        run: go test -v ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v3
